### ISSUE TITLE
migration issue on windows

### ISSUE THREAD

**Issue by xklake** [luyadev/luya-module-payment#15]
### What steps will reproduce the problem?
After install extension, running this on dos 

 ./vendor/bin/luya.bat migrate
string(15) "configs/env.php"
array(2) {
  'id' =>
  string(10) "consoleapp"
  'basePath' =>
  string(54) "C:\xampp\htdocs\pandablog.com\vendor\luyadev\luya-core"
}
Yii Migration Tool (based on Yii v2.0.25)

Error: Failed to instantiate component or class "db".

How should i do to remove this issue? i am not very familiar with Yii2. 

### What is the expected result?

No error 

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | latest
| PHP Version      |5.6
| Platform         | Apache/XAMPP/MAMPP/etc.
| Operating system | Windows/Linux Server/OSX/etc.

**Comment by xklake** [comment]
after i added db configuration into component, run again 

vendor\bin\luya.bat migrate create
string(15) "configs/env.php"
Yii Migration Tool (based on Yii v2.0.25)

No new migrations found. Your system is up-to-date.

But no data table has been created. 

when i tried the sample code to dispatch, 
It failed on 
        $integrator = Module::getInstance()->getIntegrator();

on Pay.php

**Comment by nadar** [comment]
on windows you should do `php index.php migrate` in public html folder according to the docs: https://luya.io/guide/install-windows

**Comment by xklake** [comment]
That’s not for the same plugin.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by nadar** [comment]
then i don't understand your question. because LUYA does not have a bat, so i am not sure where your bat files is from nor where this dump happens.

**Comment by xklake** [comment]
I read the document from here,

https://github.com/luyadev/luya-module-payment/blob/master/guide/setup.md


the bat for window or sh script on /vendor/bin/luya.



I have manually added DB component to fix migrate error, but nothing can be imported my database. Also it still failed to create Pay Module.

I have to switch to other payment extension due to there is not much document and it seems not too many dev are using this extension.

But thank you very much anyway, Basil.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by nadar** [comment]
The luya payment requires LUYA core and LUYA application setup, so i assume this is what was missing. its not yii2 only. Read more about LUYA if you like: https://luya.io/

Welcome! :-)

**Comment by xklake** [comment]
They are all downloaded by my composer.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by nadar** [comment]
Yes but you need the application setup like this: https://github.com/luyadev/luya-kickstarter and then add the payment module (or https://github.com/luyadev/luya-kickstarter-core or https://github.com/luyadev/luya-kickstarter-bootstrap4)

**Comment by xklake** [comment]
OMG,  I am so silly, now I realize this is not for Yii2.i must did some searches then forget to check this extension is not for yii2.  Sorry for this trouble.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by nadar** [comment]
well LUYA is Yii2 - but yes it won't work only with Yii 2 :-) 

No problem, your welcome. Try out luya.io maybe you like it
